name: Build Executable

on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set executable name
        run: echo "EXECUTABLE_NAME=ch_points${{ runner.os == 'Windows-latest' && '.exe' || '' }}" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release

      - name: List output
        run: ls -R target/release

      # Zip files on macOS and Linux
      - name: Zip Executable (macOS/Linux)
        if: runner.os != 'Windows-latest'
        run: |
          cd target/release
          zip "ch_points_${{ runner.os }}.zip" "${{ env.EXECUTABLE_NAME }}"
        shell: bash

      # Zip files on Windows
      - name: Zip Executable (Windows)
        if: runner.os == 'Windows-latest'
        run: |
          Compress-Archive -Path "target/release/${{ env.EXECUTABLE_NAME }}" -DestinationPath "target/release/ch_points_${{ runner.os }}.zip"
        shell: powershell

      # Upload Executable to Release
      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ch_points_${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
