name: Build Executable

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Zip Executable
        run: |
          cd target/release
          Compress-Archive -Path "ch_points.exe" -DestinationPath "ch_points_windows.zip"
        shell: pwsh

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ch_points_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-unix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Zip Executable
        run: |
          cd target/release
          zip "ch_points_${{ runner.os }}.zip" "ch_points"
        shell: bash

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ch_points_${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
