name: Build Executable

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set executable name
        run: echo "EXECUTABLE_NAME=ch_points${{ runner.os == 'Windows-latest' && '.exe' || '' }}" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release

      - name: List output
        run: ls -R target/release

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ env.EXECUTABLE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
