name: Build Executable

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set executable name
        run: echo "EXECUTABLE_NAME=ch_points${{ runner.os == 'Windows-latest' && '.exe' || '' }}" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release

      - name: List output
        run: ls -R target/release

      - name: Zip Executable
        run: |
          if [ "${{ runner.os }}" = "Windows-latest" ]; then
            $env:ZIP_NAME="ch_points_${{ runner.os }}.zip"
            Compress-Archive -Path "target/release/${{ env.EXECUTABLE_NAME }}" -DestinationPath "target/release/$env:ZIP_NAME"
          else
            ZIP_NAME="ch_points_${{ runner.os }}.zip"
            cd target/release
            zip $ZIP_NAME ${{ env.EXECUTABLE_NAME }}
          fi
        shell: bash | pwsh

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ch_points_${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
